800g:
    Peso: 0.8
900g:
    Peso: 0.9
1kg:
    Peso: 1.0
1,5kg:
    Peso: 1.5
2kg:
    Peso: 2.0
2,5kg:
    Peso: 2.5
3kg:
    Peso: 7.3
7kg:
    Peso: 7.0
7,5kg:
    Peso: 7.5
10,1kg:
    Peso: 10.1
12kg:
    Peso: 12.0
15kg:
    Peso: 15.0
18kg:
    Peso: 18.0
20kg:
    Peso: 20.0
25kg:
    Peso: 25.0
