cães:
  - Outra Raça
  - Aidi
  - Airedale Terrier
  - Akita
  - Algodão Tulear
  - American Foxhound
  - American Pit Bull Terrier
  - American Staffordshire Terrier
  - Anão Esquimó da América
  - Ariège Braco
  - Artois Dog
  - Azawakh
  - Barbet
  - Basenji
  - Basset Alemão da Vestfália
  - Basset Alpino
  - Basset Azul da Gasconha
  - Basset Hound
  - Basset Normando Artesiano
  - Beagle
  - Beagle Harrier
  - Bedlington Terrier
  - Bélgica Griffon
  - Bernese Mountain Dog
  - Bichon Bolonhesa
  - Bichon Frisé
  - Bichon Havanês
  - Biewer
  - Billy
  - Bloodhound
  - Blue Hiller
  - Border Collie
  - Borzoi
  - Boston Terrier
  - Bourbon Braco
  - Boxer
  - Braço Alemão
  - Braço de Auvergne
  - Braco Francês tipo Gascogne
  - Braco Francês tipo Pirineus
  - Braco Italiano
  - Brittany Fawn Griffin
  - Broholmer
  - Bruxelas Griffon
  - Buhund Norueguês
  - Bull Terrier
  - Bulldog Americano
  - Bulldog Francês
  - Bulldog Inglês
  - Bulldog Inglês Antigo
  - Bulldogge Brasileiro Inglês Antigo
  - Bullmastiff
  - Cabelo Curto Collie
  - Cabelo Longo Collie
  - Caça da Nova Zelândia
  - Cachorro Canaã
  - Cães Suíços
  - Cães Tricolores da Iugoslávia
  - Cairn Terrier
  - Canário Doggo
  - Cane Corso
  - Cão Alemão
  - Cão Bestiar
  - Cão D'água Espanhol
  - Cão D'água Frisão
  - Cão da Serra das Estrelas
  - Cão de Água Americano
  - Cão de Água Holandês Pequeno
  - Cão de Água Irlandês
  - Cão de Água Português
  - Cão de Caça
  - Cão de Crista Chinês
  - Cão de Crista Dorsal Tailandês
  - Cão de Gado Australiana
  - Cão de Halden
  - Cão de Schiller
  - Cão Eslovaco
  - Cão Eurasiano
  - Cão Holandês Pequeno
  - Cão Islandês
  - Cão Jindo Coreano
  - Cão Leãozinho
  - Cão Negro e Fogo Austríaco
  - Cão Norueguês
  - Cão Posavatz
  - Cão Tirolês
  - Cavalier King Charles Spaniel
  - Chesapeake Bay Retriever
  - Chihuahua
  - Chow Chow
  - Cocker Spaniel Americano
  - Cocker Spaniel Inglês
  - Collie Barbudo
  - Coonhound Negro e Fogo
  - Coonhound Preto e Marrom
  - Corgi Galês
  - Coton de Tulear
  - Dachshund
  - Dálmata
  - Dandie Dinmont Terrier
  - Dingo (Haliki, Warrigal, Noggum, Boolomo)
  - Doberman
  - Doggo Argentino
  - Dogue Alemão
  - Dogue Alemão do Tibete
  - Dogue de Bordéus
  - Dogue Maiorquino
  - Drenthe Partridge Spaniel
  - Drever
  - Elkhound Nnorueguês (Preto)
  - Eslovaco Cuvac
  - Eslovaco Tchouvatch
  - Esquimó Canadense (Esquimau)
  - Fila Brasileiro
  - Fogão Smaland
  - Fox Terrier
  - Foxhound Inglês
  - Francês
  - Galgo
  - Galgo Afegão
  - Galgo da Ístria
  - Galgo Escocês
  - Galgo Espanhol
  - Galgo Húngaro
  - Galgo Irlanda
  - Galgo Italiano
  - Galgo Italiano Pequeno
  - Galgo Polonês
  - Galgo Suíço
  - Galinha Rampur (Índia)
  - Gascon Saintongeois
  - Glen Irlanda de Imaal Terrier
  - Gordon Setter
  - Grande Pecuarista Suíço
  - Greyster (Noruega)
  - Griffon de Pelo de Lã
  - Griffon Nivernais
  - Grifo Apontador Eslovaco de Pêlo Duro
  - Hamilton Hound
  - Hamiltonstovare
  - Hanôver
  - Hokkaido
  - Hovawart
  - Husky Siberiano
  - Hygen Hound
  - Jack Russell Terrier
  - Jagdterrier
  - Kai
  - Kelpie
  - Kerry Beagle (Pocadan)
  - Kerry Blue Terrier
  - Kishu
  - Komondor
  - Kromfohrlander
  - Kuvasz
  - Kyi Apso (Grande Dinamarquês Tibetano Barbudo)
  - Kyi Leo
  - Labradoodle (Austrália)
  - Labrador Retriever
  - Lagotto Romagnolo
  - Laica
  - Laika
  - Lakeland Terrier
  - Lancashire Heeler (Ormskirk Terrier)
  - Landseer
  - Leonberger
  - Lhasa Apso
  - Lucas Terrier (Grã-Bretanha)
  - Lulu da Pomerânia
  - Lurcher (Grã-Bretanha)
  - Majestic Tree Hound (Estados Unidos)
  - Malamute do Alasca
  - Maltês
  - Manchester Terrier
  - Mastim
  - Mastim dos Pirinéus
  - Mastim Espanhol
  - Mastim Napolitano
  - Mastino Napolitano
  - Mountain Cur (Estados Unidos)
  - Mudi
  - Norboten Spitz
  - Norfolk Terrier
  - Norwich Terrier
  - País do buldogue
  - Papillon
  - Pastor Alemão
  - Pastor Australiano
  - Pastor Belga Groenendael
  - Pastor Belga Malinois
  - Pastor Bergamasco
  - Pastor Branco
  - Pastor Catão
  - Pastor Croata
  - Pastor da América do Norte
  - Pastor da Anatólia
  - Pastor da Ásia Central
  - Pastor da Encosta de Krast
  - Pastor da Picardia
  - Pastor da Rússia
  - Pastor de Bela
  - Pastor de Bérgamo
  - Pastor de Brie
  - Pastor de Maremma e dos Abruzos
  - Pastor de Shetland
  - Pastor dos Pireneus
  - Pastor Finlandês da Lapônia
  - Pastor Holandês
  - Pastor inglês Antigo
  - Pastor Maremmano Abruzes
  - Pastor Meridional da Rússia
  - Pastor Polonês Simples
  - Pastor Siló
  - Pastor Suíço Branco
  - Patterdale Terrier (Black Fell Terrier)
  - Pelado mexicano
  - Pelado Peruano
  - Pequinês
  - Pinscher
  - Plummer Terrier
  - Podengo Português
  - Poitevin
  - Ponteiro
  - Ponteiro Alemão
  - Poodle
  - Porcelana
  - Prazky Krysavick
  - Pudelpointer
  - Pug
  - Puli
  - Pumi
  - Rafeiro do Alentejo
  - Rastreador Brasileiro
  - Recuperador de Revestimento Plano
  - Redbone Coonhound
  - Redtick Coonhound
  - Rei Carlos Spaniel
  - Retriever da Nova Escócia
  - Retriever de Cabelo Encaracolado
  - Retriever de Cabelo Ondulado
  - Retriever de Pelo Liso
  - Retriever de Pelo Liso
  - Retriever Dourado
  - Rhodesian Ridgeback (Cão de Crista Dorsal da Rodésia)
  - Rottweiler
  - Sabujo Espanhol
  - Sabujo Finlandês
  - Sabujo Italiano
  - Sabujo Norueguês
  - Sabujo Polonês
  - Saint Germain Braco
  - Saluki
  - Samoieda
  - Sanshu
  - São Bernardo
  - Sarplaninac
  - Schapendoes
  - Schipperke
  - Schnauzer Gigante
  - Schnauzer Médio
  - Schnauzer Miniatura
  - Schnauzer Padrão
  - Sealyham Terrier
  - Seter Gordon
  - Seter Inglês
  - Seter Irlanda
  - Shar Pei
  - Shiba
  - Shih Tzu
  - Skye Terrier
  - Sloughi
  - Slougi
  - Smaland Hound
  - Smoushond
  - Spaniel Anão Continental
  - Spaniel Azul Picardia
  - Spaniel Britânico
  - Spaniel de Campo
  - Spaniel de Munster
  - Spaniel de Saint Usuge
  - Spaniel de Sussex
  - Spaniel Francês
  - Spaniel Inglês Springer
  - Spaniel Japonês
  - Spaniel Picardia
  - Spaniel Pont-Audemer
  - Spaniel Tibetano
  - Spinone Italiano
  - Spitz Alemão
  - Spitz dos Visigodos
  - Spitz Finlandês
  - Spitz Italiano
  - Spitz Japonês
  - Springer gGalês
  - Springer Inglês
  - Stabyhoun
  - Staffordshire Bull Terrier
  - Terra Nova
  - Terrier Australiano
  - Terrier Branco de Montanhas Ocidentais
  - Terrier Brasileiro
  - Terrier Checo
  - Terrier de Brinquedo Inglês
  - Terrier de Fronteira
  - Terrier de Seda
  - Terrier de Trigo Irlandesa de Pelagem Macia
  - Terrier Escocês
  - Terrier Galês
  - Terrier Irlandesa
  - Terrier Japonês
  - Terrier Miniatura Preto e Marrom
  - Terrier Preto Russo
  - Terrier Tibetano
  - Tosa
  - Treeing Walker Coonhoud
  - Trigg-Hound
  - Valentão Americano
  - Vaqueiro
  - Vendee Griffin
  - Viszla
  - Vulpino Italiano
  - Weimaraner
  - Welch Terrier
  - Whippet
  - Wolfhound Irlanda
  - York Chocolate
  - Yorkshire Terrier
